name: "Setup Trymai Scala Project"
description: "Setup Trymai Scala Project"
inputs:
  ci-token:
    description: "e.g. ${{ secrets.CI_TOKEN }}"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v13
      with:
        java-version: "adopt@1.8"

        - name: Cache sbt
          uses: actions/cache@v2
          with:
            path: |
              ~/.sbt
              ~/.ivy2/cache
              ~/.coursier/cache/v1
              ~/.cache/coursier/v1
              ~/AppData/Local/Coursier/Cache/v1
              ~/Library/Caches/Coursier/v1
            key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('project/Library.scala') }}-${{ hashFiles('project/build.properties') }}

    - name: Setup Resolvers
      env:
        CI_TOKEN: ${{ inputs.ci-token }}
      run: |
        mkdir -p ~/.sbt/1.0/plugins
        echo 'resolvers += "GitHub Package Registry (trymai)" at "https://maven.pkg.github.com/trymai/_"' > ~/.sbt/1.0/plugins/resolvers.sbt
        echo 'credentials += Credentials("GitHub Package Registry", "maven.pkg.github.com", "_", "'$CI_TOKEN'")' >> ~/.sbt/1.0/plugins/resolvers.sbt
      shell: bash
